import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

# Now import the popup server safely
import popup_server
import os
import html
import json
import socket
from pathlib import Path

import pymysql
import requests
from dotenv import load_dotenv

import popup_server

BASE_DIR = Path(__file__).resolve().parent
DEBUG = os.getenv("DEBUG", "").strip().lower() == "true"

ENV_PATH = BASE_DIR.parent.parent / ".env"
load_dotenv(ENV_PATH)

DB_HOST = os.getenv("DB_HOST")
DB_USER = os.getenv("DB_USER")
DB_PASS = os.getenv("DB_PASS")
DB_NAME = os.getenv("DB_NAME")

PUSH_TABLE = "endpoints-output-snom-push"

# Matches endpoints.py's own socket/TCP fallback (connect_endpoint_ipc).
ENDPOINT_IPC_SOCKET_PATH = "/run/openpagingserver/endpointmodules.sock"
ENDPOINT_IPC_TCP_ADDR = ("127.0.0.1", 50000)

REQUEST_TIMEOUT_SECONDS = 3
DEFAULT_MELODY = "3"  # Attention tone; set metadata["melody"] to override, or "" for none


def debug_log(message):
    if DEBUG:
        print(f"snom_message_send {message}")


def notice(message):
    # Printed explicitly to system logs so routing decisions are easily debugged
    print(f"[snom] {message}")


def db():
    return pymysql.connect(
        host=DB_HOST,
        user=DB_USER,
        password=DB_PASS,
        database=DB_NAME,
        cursorclass=pymysql.cursors.DictCursor,
    )


def parse_targets(raw_targets):
    """
    Resolves target tokens generated by OPS's normalize_targets().
    Returns (want_all: bool, ipv4s: list).
    """
    tokens = [str(t).strip() for t in (raw_targets or []) if str(t).strip()]
    if any(token.lower() == "all" for token in tokens):
        return True, []
    ipv4s = []
    for token in tokens:
        if token.startswith("snom-"):
            token = token[len("snom-"):]
        if token and token not in ipv4s:
            ipv4s.append(token)
    return False, ipv4s


def fetch_snom_targets(raw_targets):
    """Resolve raw dispatch targets ('all', 'snom-<ip>', or bare ip) to endpoint rows."""
    want_all, ipv4s = parse_targets(raw_targets)
    if not want_all and not ipv4s:
        return []
    conn = db()
    try:
        with conn.cursor() as cur:
            if want_all:
                cur.execute(
                    f"SELECT ipv4, port, use_https, username, password, status FROM `{PUSH_TABLE}`"
                )
            else:
                placeholders = ",".join(["%s"] * len(ipv4s))
                cur.execute(
                    f"SELECT ipv4, port, use_https, username, password, status "
                    f"FROM `{PUSH_TABLE}` WHERE ipv4 IN ({placeholders})",
                    tuple(ipv4s),
                )
            return cur.fetchall()
    finally:
        conn.close()


def fetch_broadcast_text(msg_id):
    """
    Look up the actual message content for a broadcast.
    Retrieves shortmessage or longmessage strings from the DB.
    """
    if not msg_id:
        return None
    conn = db()
    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT name, shortmessage, longmessage, sender FROM broadcasts WHERE id=%s LIMIT 1",
                (msg_id,),
            )
            return cur.fetchone()
    finally:
        conn.close()


def _xml_escape(value):
    return html.escape("" if value is None else str(value), quote=True)


def build_popup_xml(title, text, prompt=None, melody=None):
    # 1. First escape the raw text to make it safe for XML
    escaped_text = _xml_escape(text)
    
    # 2. Convert standard python \n newlines to real Snom <br/> tags
    # Since we escaped first, the <br/> tags stay intact and unescaped!
    formatted_text = escaped_text.replace("\n", "<br/>")

    parts = ["<?xml version=\"1.0\" encoding=\"UTF-8\"?>", "<SnomIPPhoneText>"]
    parts.append(f"<Title>{_xml_escape(title)}</Title>")
    parts.append(f"<Text>{formatted_text}</Text>")
    if prompt:
        parts.append(f"<Prompt>{_xml_escape(prompt)}</Prompt>")
    if melody:
        parts.append(f"<Melody>{_xml_escape(melody)}</Melody>")
    parts.append("</SnomIPPhoneText>")
    return "".join(parts)

def _trigger_endpoint(endpoint, popup_url):
    """
    Executes a GET trigger command to the Snom phone's built-in minibrowser
    telling it to independently fetch the compiled XML from the popup server.
    """
    scheme = "https" if endpoint.get("use_https") else "http"
    port = endpoint.get("port") or (443 if endpoint.get("use_https") else 80)
    trigger_url = f"{scheme}://{endpoint['ipv4']}:{port}/minibrowser.htm"
    auth = None
    if endpoint.get("username"):
        auth = (endpoint.get("username"), endpoint.get("password") or "")
    try:
        response = requests.get(
            trigger_url,
            params={"url": popup_url},
            auth=auth,
            timeout=REQUEST_TIMEOUT_SECONDS,
            verify=False,
        )
        ok = response.status_code < 400
        debug_log(f"trigger endpoint={endpoint['ipv4']} status={response.status_code}")
        return ok
    except Exception as exc:
        debug_log(f"trigger endpoint={endpoint['ipv4']} error={exc}")
        return False


def send_text_popup(endpoints, title, text, prompt=None, melody=None):
    """
    Publishes a SnomIPPhoneText popup payload to popup_server.py
    and notifies targeted endpoints over the network.
    """
    if not endpoints:
        return []
    xml_body = build_popup_xml(title, text, prompt=prompt, melody=melody)
    popup_url = popup_server.publish(xml_body)
    results = []
    for endpoint in endpoints:
        ok = _trigger_endpoint(endpoint, popup_url)
        results.append({"ipv4": endpoint["ipv4"], "ok": ok})
    return results


def _connect_ops_ipc(timeout=2):
    if os.name != "nt" and hasattr(socket, "AF_UNIX") and os.path.exists(ENDPOINT_IPC_SOCKET_PATH):
        sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        sock.settimeout(timeout)
        sock.connect(ENDPOINT_IPC_SOCKET_PATH)
        return sock
    return socket.create_connection(ENDPOINT_IPC_TCP_ADDR, timeout=timeout)


def send_ready_signal(module_name, stream_id):
    """
    Tells OPS this module is done handling stream_id.
    """
    sock = None
    try:
        sock = _connect_ops_ipc()
        sock.sendall(f"READY {module_name} {stream_id}\n".encode("utf-8"))
        sock.recv(1024)
    except Exception as exc:
        debug_log(f"send_ready_signal error module={module_name} stream={stream_id} error={exc}")
    finally:
        if sock is not None:
            try:
                sock.close()
            except OSError:
                pass


def handle_api(command_string):
    """
    Standalone API gateway method.
    """
    try:
        payload = json.loads(command_string)
    except Exception as exc:
        debug_log(f"handle_api invalid payload error={exc}")
        return
    targets = payload.get("targets") or []
    endpoints = fetch_snom_targets(targets)
    if not endpoints:
        debug_log(f"handle_api no matching endpoints targets={targets}")
        return
    send_text_popup(
        endpoints,
        payload.get("title") or "Message",
        payload.get("text") or "",
        prompt=payload.get("prompt"),
        melody=payload.get("melody", DEFAULT_MELODY),
    )


def handle_dispatch(action, stream_id, msg_id, targets):
    """
    Handles dispatched active broadcasts (both sendmsg and prepare_audio events).
    """
    try:
        if action not in {"sendmsg", "prepare_audio"}:
            notice(f"stream={stream_id} action={action!r} not handled")
            return

        endpoints = fetch_snom_targets(targets)
        if not endpoints:
            notice(f"stream={stream_id} msg={msg_id} NO endpoints matched targets={targets}")
            return

        broadcast = fetch_broadcast_text(msg_id)
        if not broadcast:
            notice(f"stream={stream_id} msg={msg_id} no broadcasts row found")
            return

        sender = str(broadcast.get("sender") or "").strip()
        title = str(broadcast.get("name") or "").strip() or (f"Page from {sender}" if sender else "Message")
        
        # --- NEW FORMATTING LOGIC ---
        short_msg = str(broadcast.get("shortmessage") or "").strip()
        long_msg = str(broadcast.get("longmessage") or "").strip()

        # Combine short message and long message with a double line break
        if short_msg and long_msg:
            # If both exist, display short, a blank line, then the long message
            text = f"{short_msg}\n\n{long_msg}"
        elif short_msg:
            text = short_msg
        elif long_msg:
            text = long_msg
        else:
            notice(f"stream={stream_id} msg={msg_id} broadcast has no message body - nothing to display")
            return
        # -----------------------------

        results = send_text_popup(endpoints, title, text, melody=DEFAULT_MELODY)
        notice(f"stream={stream_id} msg={msg_id} send_text_popup results={results}")
    finally:
        send_ready_signal("snom", stream_id)

def receive_audio(chunk, stream_id):
    pass


def end_stream(stream_id):
    pass