import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
if str(BASE_DIR) not in sys.path:
    sys.path.insert(0, str(BASE_DIR))

import message_send
import importlib
import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent
DEBUG = os.getenv("DEBUG", "").strip().lower() == "true"


def load_message_send():
    return importlib.import_module("snom_message_send_runtime")


message_send = load_message_send()


def page_debug(message):
    if DEBUG:
        message_send.debug_log(f"page_handler {message}")


def handle_dispatch(action, stream_id, group_id, targets, metadata=None):
    """
    Catches action="prepare_livepage". Extracts the text generated by OPS, 
    sends the popups, and immediately reports READY back upstream.
    """
    page_debug(f"handle_dispatch_start action={action} stream={stream_id} targets={targets}")
    if action != "prepare_livepage":
        return

    normalized_targets = []
    for target in targets:
        token = str(target).strip()
        if token and token not in normalized_targets:
            normalized_targets.append(token)

    if not normalized_targets:
        page_debug(f"handle_dispatch_no_targets stream={stream_id}")
        message_send.send_ready_signal("snom", stream_id)
        return

    metadata = metadata or {}
    sender = str(metadata.get("sender") or "").strip()
    
    # Extract the custom broadcast text dynamically built by the OPS core engine
    text = str(metadata.get("text") or metadata.get("message") or "").strip()
    if not text:
        text = f"Page from {sender}" if sender else "You have a page."
        
    title = str(metadata.get("title") or "").strip() or (f"Page from {sender}" if sender else "Live Page")
    prompt = metadata.get("prompt")
    melody = metadata.get("melody", message_send.DEFAULT_MELODY)

    ipv4s = message_send.parse_targets(normalized_targets)
    endpoints = message_send.fetch_snom_targets(ipv4s)

    if endpoints:
        results = message_send.send_text_popup(endpoints, title, text, prompt=prompt, melody=melody)
        page_debug(f"handle_dispatch_results stream={stream_id} results={results}")
    else:
        page_debug(f"handle_dispatch_skipped: No active target profiles online.")

    # Signal ready right away so OPS doesn't block or stall waiting for an audio track
    message_send.send_ready_signal("snom", stream_id)